import { Component, createContext, memo, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import { getWidget, validateDashboard, type DashboardConfig, type DashboardWidget, type DataRecord, type Primitive, type ThemeTokens } from '@dashboard-generator/core';
import { FiltersContext, useFilterStore, useFilters } from '@dashboard-generator/filters';
import { gridStyle } from '@dashboard-generator/layout';
import { darkTheme, lightTheme, ThemeContext, useTheme } from '@dashboard-generator/theme';
import { loadData } from '@dashboard-generator/datasource';
import '@dashboard-generator/widgets';
export * from '@dashboard-generator/core'; export { useFilters } from '@dashboard-generator/filters'; export { useTheme } from '@dashboard-generator/theme';

interface DashboardContextValue { config: DashboardConfig; theme: ThemeTokens }
const DashboardContext = createContext<DashboardContextValue | null>(null);
export const useDashboard = () => { const value = useContext(DashboardContext); if (!value) throw new Error('useDashboard must be used inside DashboardProvider'); return value; };
export function DashboardProvider({ config, children }: { config: DashboardConfig; children: ReactNode }) { const validated = useMemo(() => validateDashboard(config), [config]); const theme = typeof validated.theme === 'object' ? { ...lightTheme, ...validated.theme } : validated.theme === 'dark' ? darkTheme : lightTheme; const initialFilters = useMemo(() => Object.fromEntries((validated.filters ?? []).map(f => [f.id, f.defaultValue ?? null])), [validated.filters]); const store = useFilterStore(initialFilters); return <DashboardContext.Provider value={{ config:validated, theme }}><ThemeContext.Provider value={theme}><FiltersContext.Provider value={store}>{children}</FiltersContext.Provider></ThemeContext.Provider></DashboardContext.Provider>; }
class WidgetBoundary extends Component<{ children: ReactNode; fallback: ReactNode }, { failed: boolean }> { state = { failed:false }; static getDerivedStateFromError() { return { failed:true }; } render() { return this.state.failed ? this.props.fallback : this.props.children; } }
function useWidgetData(widget: DashboardWidget) { const [state, setState] = useState<{data:DataRecord[]; loading:boolean; error?:Error}>({ data:[], loading:!!widget.datasource }); useEffect(() => { let active = true; if (!widget.datasource) { setState({data:[],loading:false}); return; } setState(s => ({...s,loading:true,error:undefined})); loadData(widget.datasource).then(result => active && setState({data:result.data,loading:false})).catch((error:unknown) => active && setState({data:[],loading:false,error:error instanceof Error ? error : new Error('Data loading failed')})); return () => { active=false; }; }, [widget.datasource]); return state; }
const filterData = (data: DataRecord[], filters: Record<string, Primitive>, config: DashboardConfig) => data.filter(row => (config.filters ?? []).every(filter => { const value = filters[filter.id]; if (value === null || value === '' || value === false || value === undefined || !filter.field) return true; const cell = String(row[filter.field] ?? '').toLowerCase(); return filter.type === 'search' ? cell.includes(String(value).toLowerCase()) : cell === String(value).toLowerCase(); }));
const WidgetFrame = memo(({ widget }: { widget: DashboardWidget }) => { const { config, theme } = useDashboard(); const { values } = useFilters(); const state = useWidgetData(widget); const definition = getWidget(widget.type); const data = filterData(state.data, values, config); const props = { widget, data, loading:state.loading, error:state.error, filters:values, theme }; const fallback = <div className="dg-error">This widget could not be rendered.</div>; return <section className="dg-card" style={{...gridStyle(widget.position), ...widget.style, background:theme.surface, borderColor:theme.border}} aria-label={widget.title ?? widget.type}><header>{widget.title && <h2>{widget.title}</h2>}</header><div className="dg-content">{state.loading ? <div className="dg-empty">Loading…</div> : state.error ? <div className="dg-error">{state.error.message}</div> : !definition ? <div className="dg-error">Unknown widget type: {widget.type}</div> : <WidgetBoundary fallback={fallback}>{definition.renderer(props)}</WidgetBoundary>}</div></section>; });
function FilterBar() { const { config } = useDashboard(); const { values, setValue } = useFilters(); if (!config.filters?.length) return null; return <div className="dg-filters" aria-label="Dashboard filters">{config.filters.map(filter => <label key={filter.id}>{filter.label}{filter.type === 'select' || filter.type === 'radio' ? <select value={String(values[filter.id] ?? '')} onChange={e => setValue(filter.id,e.target.value)}><option value="">All</option>{filter.options?.map(option => <option value={String(option.value)} key={String(option.value)}>{option.label}</option>)}</select> : <input type={filter.type === 'date' ? 'date' : filter.type === 'checkbox' ? 'checkbox' : 'search'} value={filter.type === 'checkbox' ? undefined : String(values[filter.id] ?? '')} onChange={e => setValue(filter.id, filter.type === 'checkbox' ? e.currentTarget.checked : e.currentTarget.value)} />}</label>)}</div> }
function DashboardCanvas() { const { config, theme } = useDashboard(); return <main className="dg-dashboard" style={{ background:theme.background, color:theme.text, fontFamily:theme.font }}><div className="dg-heading"><div><h1>{config.title}</h1>{config.description && <p>{config.description}</p>}</div></div><FilterBar /><div className="dg-grid">{config.widgets.map(widget => <WidgetFrame key={widget.id} widget={widget} />)}</div></main> }
export function DashboardRenderer({ config }: { config: DashboardConfig }) { return <DashboardProvider config={config}><DashboardCanvas /></DashboardProvider>; }
